### ISSUE TITLE
There is no option to decode text

### ISSUE THREAD

**Issue by samthelion17** [dandeto/Base-64-Extension#2]
It would be useful to have an option to decode base64-encoded text, since many link shorteners and other web pages use this to encode urls and other suff.

**Comment by dandeto** [comment]
You're right, encoding and decoding text without loading a .txt file is a basic feature that this extension should already have! I'm going to get on that. Will close when completed. Thanks for bringing this up.

**Comment by dandeto** [comment]
Alright, it's on the chrome webstore now with the ability to encode and decode text! I appreciate your interest and feedback for this extension.
